export interface BankWord {
  char: string
  pinyin: string
  meaning: string
  example: string
  hsk: string
  cat: string
}

export const WORD_BANK: BankWord[] = [
  {char:'你好',pinyin:'nǐ hǎo',meaning:'Hello',example:'你好！你叫什么名字？',hsk:'HSK1',cat:'Greetings'},
  {char:'谢谢',pinyin:'xiè xiè',meaning:'Thank you',example:'谢谢你的帮助！',hsk:'HSK1',cat:'Greetings'},
  {char:'不客气',pinyin:'bú kè qi',meaning:'You are welcome',example:'谢谢！—不客气。',hsk:'HSK1',cat:'Greetings'},
  {char:'对不起',pinyin:'duì bu qǐ',meaning:'Sorry',example:'对不起，我来晚了。',hsk:'HSK1',cat:'Greetings'},
  {char:'没关系',pinyin:'méi guān xi',meaning:'It is okay',example:'对不起！—没关系。',hsk:'HSK1',cat:'Greetings'},
  {char:'再见',pinyin:'zài jiàn',meaning:'Goodbye',example:'明天见！再见！',hsk:'HSK1',cat:'Greetings'},
  {char:'是',pinyin:'shì',meaning:'Yes / to be',example:'他是我的朋友。',hsk:'HSK1',cat:'Daily life'},
  {char:'不是',pinyin:'bú shì',meaning:'No / is not',example:'这不是我的书。',hsk:'HSK1',cat:'Daily life'},
  {char:'我',pinyin:'wǒ',meaning:'I / me',example:'我是学生。',hsk:'HSK1',cat:'Daily life'},
  {char:'你',pinyin:'nǐ',meaning:'You',example:'你叫什么名字？',hsk:'HSK1',cat:'Daily life'},
  {char:'他',pinyin:'tā',meaning:'He / him',example:'他是老师。',hsk:'HSK1',cat:'Daily life'},
  {char:'她',pinyin:'tā',meaning:'She / her',example:'她很漂亮。',hsk:'HSK1',cat:'Daily life'},
  {char:'我们',pinyin:'wǒ men',meaning:'We / us',example:'我们是朋友。',hsk:'HSK1',cat:'Daily life'},
  {char:'这',pinyin:'zhè',meaning:'This',example:'这是什么？',hsk:'HSK1',cat:'Daily life'},
  {char:'那',pinyin:'nà',meaning:'That',example:'那是我的书。',hsk:'HSK1',cat:'Daily life'},
  {char:'什么',pinyin:'shén me',meaning:'What',example:'这是什么？',hsk:'HSK1',cat:'Daily life'},
  {char:'哪里',pinyin:'nǎ lǐ',meaning:'Where',example:'你在哪里？',hsk:'HSK1',cat:'Travel'},
  {char:'为什么',pinyin:'wèi shén me',meaning:'Why',example:'你为什么哭？',hsk:'HSK1',cat:'Daily life'},
  {char:'怎么',pinyin:'zěn me',meaning:'How',example:'你怎么去学校？',hsk:'HSK1',cat:'Daily life'},
  {char:'多少',pinyin:'duō shǎo',meaning:'How many / how much',example:'这多少钱？',hsk:'HSK1',cat:'Numbers'},
  {char:'一',pinyin:'yī',meaning:'One',example:'我有一个苹果。',hsk:'HSK1',cat:'Numbers'},
  {char:'二',pinyin:'èr',meaning:'Two',example:'我有二个哥哥。',hsk:'HSK1',cat:'Numbers'},
  {char:'三',pinyin:'sān',meaning:'Three',example:'请给我三杯水。',hsk:'HSK1',cat:'Numbers'},
  {char:'四',pinyin:'sì',meaning:'Four',example:'四月是春天。',hsk:'HSK1',cat:'Numbers'},
  {char:'五',pinyin:'wǔ',meaning:'Five',example:'我有五本书。',hsk:'HSK1',cat:'Numbers'},
  {char:'六',pinyin:'liù',meaning:'Six',example:'今天是六号。',hsk:'HSK1',cat:'Numbers'},
  {char:'七',pinyin:'qī',meaning:'Seven',example:'一周有七天。',hsk:'HSK1',cat:'Numbers'},
  {char:'八',pinyin:'bā',meaning:'Eight',example:'八月很热。',hsk:'HSK1',cat:'Numbers'},
  {char:'九',pinyin:'jiǔ',meaning:'Nine',example:'九月开学了。',hsk:'HSK1',cat:'Numbers'},
  {char:'十',pinyin:'shí',meaning:'Ten',example:'我学习了十个词。',hsk:'HSK1',cat:'Numbers'},
  {char:'今天',pinyin:'jīn tiān',meaning:'Today',example:'今天天气很好。',hsk:'HSK1',cat:'Time'},
  {char:'明天',pinyin:'míng tiān',meaning:'Tomorrow',example:'明天我有考试。',hsk:'HSK1',cat:'Time'},
  {char:'昨天',pinyin:'zuó tiān',meaning:'Yesterday',example:'昨天我去了超市。',hsk:'HSK1',cat:'Time'},
  {char:'现在',pinyin:'xiàn zài',meaning:'Now',example:'现在几点了？',hsk:'HSK1',cat:'Time'},
  {char:'吃',pinyin:'chī',meaning:'To eat',example:'我想吃饭。',hsk:'HSK1',cat:'Food'},
  {char:'喝',pinyin:'hē',meaning:'To drink',example:'我喝水。',hsk:'HSK1',cat:'Food'},
  {char:'饭',pinyin:'fàn',meaning:'Rice / meal',example:'我们一起吃饭吧。',hsk:'HSK1',cat:'Food'},
  {char:'水',pinyin:'shuǐ',meaning:'Water',example:'请给我一杯水。',hsk:'HSK1',cat:'Food'},
  {char:'茶',pinyin:'chá',meaning:'Tea',example:'你喝茶吗？',hsk:'HSK1',cat:'Food'},
  {char:'书',pinyin:'shū',meaning:'Book',example:'这本书很有意思。',hsk:'HSK1',cat:'Daily life'},
  {char:'手机',pinyin:'shǒu jī',meaning:'Mobile phone',example:'我的手机没电了。',hsk:'HSK1',cat:'Daily life'},
  {char:'钱',pinyin:'qián',meaning:'Money',example:'这个多少钱？',hsk:'HSK1',cat:'Shopping'},
  {char:'人',pinyin:'rén',meaning:'Person / people',example:'这里有很多人。',hsk:'HSK1',cat:'Daily life'},
  {char:'学生',pinyin:'xué shēng',meaning:'Student',example:'我是大学生。',hsk:'HSK1',cat:'Work'},
  {char:'老师',pinyin:'lǎo shī',meaning:'Teacher',example:'我的老师很好。',hsk:'HSK1',cat:'Work'},
  {char:'朋友',pinyin:'péng yǒu',meaning:'Friend',example:'他是我的好朋友。',hsk:'HSK1',cat:'Daily life'},
  {char:'爸爸',pinyin:'bà ba',meaning:'Father',example:'我爸爸是医生。',hsk:'HSK1',cat:'Family'},
  {char:'妈妈',pinyin:'mā ma',meaning:'Mother',example:'我妈妈很漂亮。',hsk:'HSK1',cat:'Family'},
  {char:'去',pinyin:'qù',meaning:'To go',example:'我去图书馆。',hsk:'HSK1',cat:'Verbs'},
  {char:'来',pinyin:'lái',meaning:'To come',example:'你来我家吧。',hsk:'HSK1',cat:'Verbs'},
  {char:'看',pinyin:'kàn',meaning:'To look / watch',example:'我看书。',hsk:'HSK1',cat:'Verbs'},
  {char:'听',pinyin:'tīng',meaning:'To listen',example:'我听音乐。',hsk:'HSK1',cat:'Verbs'},
  {char:'说',pinyin:'shuō',meaning:'To speak',example:'请说慢一点。',hsk:'HSK1',cat:'Verbs'},
  {char:'写',pinyin:'xiě',meaning:'To write',example:'请写你的名字。',hsk:'HSK1',cat:'Verbs'},
  {char:'学习',pinyin:'xué xí',meaning:'To study',example:'我每天学习中文。',hsk:'HSK1',cat:'Verbs'},
  {char:'有',pinyin:'yǒu',meaning:'To have',example:'我有一个苹果。',hsk:'HSK1',cat:'Verbs'},
  {char:'没有',pinyin:'méi yǒu',meaning:'Do not have',example:'我没有钱。',hsk:'HSK1',cat:'Verbs'},
  {char:'喜欢',pinyin:'xǐ huān',meaning:'To like',example:'我喜欢打篮球。',hsk:'HSK1',cat:'Verbs'},
  {char:'想',pinyin:'xiǎng',meaning:'To want / think',example:'我想喝水。',hsk:'HSK1',cat:'Verbs'},
  {char:'好',pinyin:'hǎo',meaning:'Good',example:'这个菜很好吃。',hsk:'HSK1',cat:'Adjectives'},
  {char:'大',pinyin:'dà',meaning:'Big / large',example:'这个房间很大。',hsk:'HSK1',cat:'Adjectives'},
  {char:'小',pinyin:'xiǎo',meaning:'Small',example:'这只猫很小。',hsk:'HSK1',cat:'Adjectives'},
  {char:'热',pinyin:'rè',meaning:'Hot',example:'今天天气很热。',hsk:'HSK1',cat:'Adjectives'},
  {char:'冷',pinyin:'lěng',meaning:'Cold',example:'冬天很冷。',hsk:'HSK1',cat:'Adjectives'},
  {char:'高兴',pinyin:'gāo xìng',meaning:'Happy',example:'见到你我很高兴。',hsk:'HSK1',cat:'Emotions'},
  // HSK2
  {char:'帮助',pinyin:'bāng zhù',meaning:'To help',example:'谢谢你帮助我。',hsk:'HSK2',cat:'Verbs'},
  {char:'等',pinyin:'děng',meaning:'To wait',example:'请等一下。',hsk:'HSK2',cat:'Verbs'},
  {char:'找',pinyin:'zhǎo',meaning:'To look for',example:'我在找我的手机。',hsk:'HSK2',cat:'Verbs'},
  {char:'买',pinyin:'mǎi',meaning:'To buy',example:'我要买一件衣服。',hsk:'HSK2',cat:'Shopping'},
  {char:'卖',pinyin:'mài',meaning:'To sell',example:'这家店卖手机。',hsk:'HSK2',cat:'Shopping'},
  {char:'走',pinyin:'zǒu',meaning:'To walk / leave',example:'我们走路去吧。',hsk:'HSK2',cat:'Verbs'},
  {char:'问',pinyin:'wèn',meaning:'To ask',example:'我问老师一个问题。',hsk:'HSK2',cat:'Verbs'},
  {char:'告诉',pinyin:'gào su',meaning:'To tell',example:'请告诉我你的名字。',hsk:'HSK2',cat:'Verbs'},
  {char:'给',pinyin:'gěi',meaning:'To give',example:'我给你一本书。',hsk:'HSK2',cat:'Verbs'},
  {char:'因为',pinyin:'yīn wèi',meaning:'Because',example:'因为下雨，我没去。',hsk:'HSK2',cat:'Daily life'},
  {char:'所以',pinyin:'suǒ yǐ',meaning:'Therefore',example:'所以我不去了。',hsk:'HSK2',cat:'Daily life'},
  {char:'但是',pinyin:'dàn shì',meaning:'But / however',example:'我想去，但是没时间。',hsk:'HSK2',cat:'Daily life'},
  {char:'已经',pinyin:'yǐ jīng',meaning:'Already',example:'我已经吃了。',hsk:'HSK2',cat:'Daily life'},
  {char:'非常',pinyin:'fēi cháng',meaning:'Very / extremely',example:'这道菜非常好吃。',hsk:'HSK2',cat:'Adjectives'},
  {char:'学校',pinyin:'xué xiào',meaning:'School',example:'我的学校很大。',hsk:'HSK2',cat:'Travel'},
  {char:'医院',pinyin:'yī yuàn',meaning:'Hospital',example:'他去医院看病。',hsk:'HSK2',cat:'Health'},
  {char:'超市',pinyin:'chāo shì',meaning:'Supermarket',example:'我去超市买东西。',hsk:'HSK2',cat:'Shopping'},
  {char:'餐厅',pinyin:'cān tīng',meaning:'Restaurant',example:'我们去餐厅吃饭。',hsk:'HSK2',cat:'Food'},
  {char:'公司',pinyin:'gōng sī',meaning:'Company',example:'他在大公司工作。',hsk:'HSK2',cat:'Work'},
  {char:'飞机',pinyin:'fēi jī',meaning:'Airplane',example:'我坐飞机去北京。',hsk:'HSK2',cat:'Travel'},
  // HSK3
  {char:'努力',pinyin:'nǔ lì',meaning:'To work hard',example:'你要努力学习。',hsk:'HSK3',cat:'Work'},
  {char:'成功',pinyin:'chéng gōng',meaning:'Success',example:'祝你成功！',hsk:'HSK3',cat:'Work'},
  {char:'问题',pinyin:'wèn tí',meaning:'Problem / question',example:'你有什么问题？',hsk:'HSK3',cat:'Daily life'},
  {char:'决定',pinyin:'jué dìng',meaning:'To decide',example:'我决定去中国。',hsk:'HSK3',cat:'Daily life'},
  {char:'担心',pinyin:'dān xīn',meaning:'To worry',example:'我很担心你。',hsk:'HSK3',cat:'Emotions'},
  {char:'生气',pinyin:'shēng qì',meaning:'Angry',example:'他为什么生气？',hsk:'HSK3',cat:'Emotions'},
  {char:'健康',pinyin:'jiàn kāng',meaning:'Health / healthy',example:'身体健康最重要。',hsk:'HSK3',cat:'Health'},
  {char:'运动',pinyin:'yùn dòng',meaning:'Exercise / sport',example:'每天运动有益健康。',hsk:'HSK3',cat:'Health'},
  {char:'天气',pinyin:'tiān qì',meaning:'Weather',example:'今天天气怎么样？',hsk:'HSK3',cat:'Nature'},
  {char:'便宜',pinyin:'pián yi',meaning:'Cheap',example:'这个东西很便宜。',hsk:'HSK3',cat:'Shopping'},
  {char:'贵',pinyin:'guì',meaning:'Expensive',example:'这件衣服太贵了。',hsk:'HSK3',cat:'Shopping'},
  {char:'外卖',pinyin:'wài mài',meaning:'Food delivery',example:'我叫了外卖。',hsk:'HSK3',cat:'Food'},
  // HSK4+
  {char:'效率',pinyin:'xiào lǜ',meaning:'Efficiency',example:'提高工作效率很重要。',hsk:'HSK4',cat:'Work'},
  {char:'责任',pinyin:'zé rèn',meaning:'Responsibility',example:'你要负责任。',hsk:'HSK4',cat:'Work'},
  {char:'建议',pinyin:'jiàn yì',meaning:'Suggestion',example:'我有一个建议。',hsk:'HSK4',cat:'Daily life'},
  {char:'网络',pinyin:'wǎng luò',meaning:'Internet',example:'网络速度很慢。',hsk:'HSK4',cat:'Daily life'},
  {char:'市场',pinyin:'shì chǎng',meaning:'Market',example:'这个市场很大。',hsk:'HSK4',cat:'Work'},
  // Business
  {char:'样品',pinyin:'yàng pǐn',meaning:'Sample / prototype',example:'我想要一个样品。',hsk:'HSK4',cat:'Business'},
  {char:'批发',pinyin:'pī fā',meaning:'Wholesale',example:'批发价格是多少？',hsk:'HSK4',cat:'Business'},
  {char:'工厂',pinyin:'gōng chǎng',meaning:'Factory',example:'这个工厂在哪里？',hsk:'HSK3',cat:'Business'},
  {char:'供应商',pinyin:'gōng yìng shāng',meaning:'Supplier',example:'我们需要找一个好供应商。',hsk:'HSK4',cat:'Business'},
  {char:'报价',pinyin:'bào jià',meaning:'Quote / price quotation',example:'请给我报价。',hsk:'HSK4',cat:'Business'},
  {char:'折扣',pinyin:'zhé kòu',meaning:'Discount',example:'有折扣吗？',hsk:'HSK4',cat:'Business'},
  {char:'付款',pinyin:'fù kuǎn',meaning:'Payment',example:'怎么付款？',hsk:'HSK4',cat:'Business'},
  {char:'快递',pinyin:'kuài dì',meaning:'Express delivery',example:'用快递寄过去。',hsk:'HSK3',cat:'Business'},
  {char:'合同',pinyin:'hé tong',meaning:'Contract',example:'我们需要签合同。',hsk:'HSK3',cat:'Business'},
  {char:'微信',pinyin:'wēi xìn',meaning:'WeChat',example:'你的微信是什么？',hsk:'HSK3',cat:'Business'},
  {char:'创业',pinyin:'chuàng yè',meaning:'Start a business',example:'他决定创业。',hsk:'HSK5',cat:'Work'},
  {char:'贸易',pinyin:'mào yì',meaning:'Trade',example:'两国的贸易增加了。',hsk:'HSK5',cat:'Work'},
  {char:'谈判',pinyin:'tán pàn',meaning:'Negotiation',example:'谈判进行得很顺利。',hsk:'HSK5',cat:'Work'},
  {char:'风险',pinyin:'fēng xiǎn',meaning:'Risk',example:'这个投资有风险。',hsk:'HSK5',cat:'Work'},
]

export const WORD_BANK_CATS = [...new Set(WORD_BANK.map(w => w.cat))].sort()
export const WORD_BANK_HSK  = ['HSK1','HSK2','HSK3','HSK4','HSK5','HSK6']
